// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server.DataModels;

namespace Server.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210308193336_AddInspectionPhotosAndUsers")]
    partial class AddInspectionPhotosAndUsers
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Server.DataModels.Colony.Area", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("System");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 3, 8, 14, 33, 36, 34, DateTimeKind.Local).AddTicks(4039));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("System");

                    b.Property<DateTime>("LastModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 3, 8, 14, 33, 36, 34, DateTimeKind.Local).AddTicks(4356));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Area");
                });

            modelBuilder.Entity("Server.DataModels.Colony.Colony", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("text");

                    b.Property<Guid>("AreaId")
                        .HasColumnType("uuid");

                    b.Property<string>("BroodChamberType")
                        .HasColumnType("text");

                    b.Property<string>("ColonyNumber")
                        .HasColumnType("text");

                    b.Property<string>("ColonySource")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("System");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 3, 8, 14, 33, 36, 36, DateTimeKind.Local).AddTicks(2390));

                    b.Property<string>("GeneticBreed")
                        .HasColumnType("text");

                    b.Property<int>("HiveNumber")
                        .HasColumnType("integer");

                    b.Property<string>("HiveType")
                        .HasColumnType("text");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("InstallDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("InstallationType")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("System");

                    b.Property<DateTime>("LastModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 3, 8, 14, 33, 36, 36, DateTimeKind.Local).AddTicks(2740));

                    b.Property<string>("Markings")
                        .HasColumnType("text");

                    b.Property<Guid?>("PhotoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("QueenExclude")
                        .HasColumnType("boolean");

                    b.Property<string>("QueenType")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("HostId");

                    b.HasIndex("PhotoId");

                    b.ToTable("Colony");
                });

            modelBuilder.Entity("Server.DataModels.Colony.Host", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("System");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 3, 8, 14, 33, 36, 38, DateTimeKind.Local).AddTicks(4234));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("System");

                    b.Property<DateTime>("LastModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 3, 8, 14, 33, 36, 38, DateTimeKind.Local).AddTicks(4577));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Host");
                });

            modelBuilder.Entity("Server.DataModels.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("System");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 3, 8, 14, 33, 36, 19, DateTimeKind.Local).AddTicks(8831));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("System");

                    b.Property<DateTime>("LastModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 3, 8, 14, 33, 36, 23, DateTimeKind.Local).AddTicks(2708));

                    b.Property<string>("Path")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Photo");
                });

            modelBuilder.Entity("Server.DataModels.SpecialInspection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ColonyId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("System");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 3, 8, 14, 33, 36, 25, DateTimeKind.Local).AddTicks(2969));

                    b.Property<string[]>("Feeds")
                        .HasColumnType("text[]");

                    b.Property<string>("Growth")
                        .HasColumnType("text");

                    b.Property<string[]>("Harvest")
                        .HasColumnType("text[]");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("System");

                    b.Property<DateTime>("LastModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 3, 8, 14, 33, 36, 25, DateTimeKind.Local).AddTicks(3334));

                    b.Property<Guid?>("PhotoId")
                        .HasColumnType("uuid");

                    b.Property<string[]>("TreatmentDetails")
                        .HasColumnType("text[]");

                    b.Property<string[]>("Treatments")
                        .HasColumnType("text[]");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uuid");

                    b.Property<string[]>("Wintering")
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("ColonyId");

                    b.HasIndex("PhotoId");

                    b.HasIndex("UserID");

                    b.ToTable("SpecialInspection");
                });

            modelBuilder.Entity("Server.DataModels.TypicalInspection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brood")
                        .HasColumnType("text");

                    b.Property<int>("BroodChambers")
                        .HasColumnType("integer");

                    b.Property<string>("BroodPattern")
                        .HasColumnType("text");

                    b.Property<string>("Cells")
                        .HasColumnType("text");

                    b.Property<Guid>("ColonyId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("System");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 3, 8, 14, 33, 36, 31, DateTimeKind.Local).AddTicks(449));

                    b.Property<bool>("Excluder")
                        .HasColumnType("boolean");

                    b.Property<string>("Fitness")
                        .HasColumnType("text");

                    b.Property<string[]>("Growth")
                        .HasColumnType("text[]");

                    b.Property<string>("HiveBottom")
                        .HasColumnType("text");

                    b.Property<string>("Honey")
                        .HasColumnType("text");

                    b.Property<int>("HoneyChamber")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string[]>("Issues")
                        .HasColumnType("text[]");

                    b.Property<string>("LastModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("System");

                    b.Property<DateTime>("LastModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 3, 8, 14, 33, 36, 31, DateTimeKind.Local).AddTicks(807));

                    b.Property<string>("Mood")
                        .HasColumnType("text");

                    b.Property<bool>("MouseGuard")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PhotoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("PollenCollector")
                        .HasColumnType("boolean");

                    b.Property<string>("Population")
                        .HasColumnType("text");

                    b.Property<string[]>("Seasonal")
                        .HasColumnType("text[]");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("SwarmStatus")
                        .HasColumnType("text");

                    b.Property<Guid?>("UserID")
                        .HasColumnType("uuid");

                    b.Property<string>("Vents")
                        .HasColumnType("text");

                    b.Property<bool>("WaspGuard")
                        .HasColumnType("boolean");

                    b.Property<string[]>("Weather")
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("ColonyId");

                    b.HasIndex("PhotoId");

                    b.HasIndex("UserID");

                    b.ToTable("TypicalInspection");
                });

            modelBuilder.Entity("Server.DataModels.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("System");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 3, 8, 14, 33, 36, 33, DateTimeKind.Local).AddTicks(1635));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastModifiedBy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("System");

                    b.Property<DateTime>("LastModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValue(new DateTime(2021, 3, 8, 14, 33, 36, 33, DateTimeKind.Local).AddTicks(1998));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Server.DataModels.Colony.Colony", b =>
                {
                    b.HasOne("Server.DataModels.Colony.Area", "Area")
                        .WithMany("Colonies")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.DataModels.Colony.Host", "Host")
                        .WithMany("Colonies")
                        .HasForeignKey("HostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.DataModels.Photo", "Photo")
                        .WithMany("Colonies")
                        .HasForeignKey("PhotoId");

                    b.Navigation("Area");

                    b.Navigation("Host");

                    b.Navigation("Photo");
                });

            modelBuilder.Entity("Server.DataModels.SpecialInspection", b =>
                {
                    b.HasOne("Server.DataModels.Colony.Colony", "Colony")
                        .WithMany()
                        .HasForeignKey("ColonyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.DataModels.Photo", "Photo")
                        .WithMany("SpecialInspections")
                        .HasForeignKey("PhotoId");

                    b.HasOne("Server.DataModels.User", "User")
                        .WithMany("SpecialInspections")
                        .HasForeignKey("UserID");

                    b.Navigation("Colony");

                    b.Navigation("Photo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.DataModels.TypicalInspection", b =>
                {
                    b.HasOne("Server.DataModels.Colony.Colony", "Colony")
                        .WithMany()
                        .HasForeignKey("ColonyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.DataModels.Photo", "Photo")
                        .WithMany("TypicalInspections")
                        .HasForeignKey("PhotoId");

                    b.HasOne("Server.DataModels.User", "User")
                        .WithMany("TypicalInspections")
                        .HasForeignKey("UserID");

                    b.Navigation("Colony");

                    b.Navigation("Photo");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.DataModels.Colony.Area", b =>
                {
                    b.Navigation("Colonies");
                });

            modelBuilder.Entity("Server.DataModels.Colony.Host", b =>
                {
                    b.Navigation("Colonies");
                });

            modelBuilder.Entity("Server.DataModels.Photo", b =>
                {
                    b.Navigation("Colonies");

                    b.Navigation("SpecialInspections");

                    b.Navigation("TypicalInspections");
                });

            modelBuilder.Entity("Server.DataModels.User", b =>
                {
                    b.Navigation("SpecialInspections");

                    b.Navigation("TypicalInspections");
                });
#pragma warning restore 612, 618
        }
    }
}
